version: '3.7'

services:
  server:
    image: "menoncello/podcast-manager.api"
    environment:
      MongoUrl: ${MONGO_URL}
      RabbitUrl: ${RABBIT_URL}
      ListenUrl: ${API_URL}
    ports:
      - target: 80
        published: 5555
        mode: host
    networks:
      - caddy_default
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

networks:
  caddy_default:
    external: true