version: '3.7'

services:
  updater:
    image: "menoncello/podcast-manager.api"
    environment:
      MongoUrl: ${MONGO_URL}
      RabbitUrl: ${RABBIT_URL}
      ListenUrl: ${API_URL}
    ports:
      - "5555:5555"
    networks:
      - backend
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager

networks:
  backend:
    external: true