version: '3.7'

services:
  server:
    image: "menoncello/podcast-manager.api"
    environment:
      MongoUrl: ${MONGO_URL}
      RabbitUrl: ${RABBIT_URL}
      ListenUrl: ${API_URL}
    ports:
      - "5555:80"
    networks:
      - backend
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

networks:
  backend:
    external: true